server:
  port: 81

spring:
  redis:
    host: localhost
  datasource:
    hikari:
      connection-init-sql: SET NAMES utf8mb4
    url: jdbc:mysql://${REDROCK_CORE_DB_HOST}:${REDROCK_CORE_DB_PORT}/${REDROCK_CORE_DB_DBNAME}?useUnicode=true&useSSL=false&serverTimezone=UTC
    username: ${REDROCK_CORE_DB_USERNAME}
    password: ${REDROCK_CORE_DB_PASSWORD}